import React, { useState } from "react";
import "./styles.css";

var emojiDictionary = {
  "😡": "angry",
  "❤": "heart",
  "😂": "laugh",
  "😘": "kiss",
  "👏": "clap",
  "😎": "kool kidz",
  "🥱": "yawn",
  "🍇": "Grapes",
  "🍈": "Melon",
  "🍉": "Watermelon",
  "🍊": "Tangerine",
  "🍋": "Lemon",
  "🍌": "Banana",
  "🍍": "Pineapple",
  "🥭": "Mango",
  "🍎": "Red Apple",
  "🍏": "Green Apple",
  "🍐": "Pear",
  "🍑": "Peach",
  "🍒": "Cherries",
  "🍓": "Strawberry",
  "🫐": "Blueberries",
  "🥝": "Kiwi Fruit",
  "🍅": "Tomato",
  "🫒": "Olive",
  "🥥": "Coconut",
  "🥑": "Avocado",
  "🍆": "Eggplant",
  "🥔": "Potato",
  "🥕": "Carrot",
  "🌽": "Ear of Corn",
  "🫑": "Bell Pepper",
  "🥒": "Cucumber",
  "🥬": "Leafy Green",
  "🥦": "Broccoli",
  "🧄": "Garlic",
  "🧅": "Onion",
  "🍄": "Mushroom",
  "🥜": "Peanuts",
  "🌰": "Chestnut",
  "🍞": "Bread",
  "🥐": "Croissant",
  "🥖": "Baguette Bread",
  "🫓": "Flatbread",
  "🥨": "Pretzel",
  "🥯": "Bagel",
  "🥞": "Pancakes",
  "🧇": "Waffle",
  "🧀": "Cheese Wedge",
  "🍖": "Meat on Bone",
  "🍗": "Poultry Leg",
  "🥩": "Cut of Meat",
  "🥓": "Bacon",
  "🍔": "Hamburger",
  "🍟": "French Fries",
  "🍕": "Pizza",
  "🌭": "Hot Dog",
  "🥪": "Sandwich",
  "🌮": "Taco",
  "🌯": "Burrito",
  "🫔": "Tamale",
  "🥙": "Stuffed Flatbread",
  "🧆": "Falafel",
  "🥚": "Egg",
  "🍳": "Cooking",
  "🥘": "Shallow Pan of Food",
  "🍲": "Pot of Food",
  "🫕": "Fondue",
  "🥣": "Bowl with Spoon",
  "🥗": "Green Salad",
  "🍿": "Popcorn",
  "🧈": "Butter",
  "🧂": "Salt",
  "🥫": "Canned Food",
  "🍱": "Bento Box",
  "🍘": "Rice Cracker",
  "🍙": "Rice Ball",
  "🍚": "Cooked Rice",
  "🍛": "Curry Rice",
  "🍜": "Steaming Bowl",
  "🍝": "Spaghetti",
  "🍠": "Roasted Sweet Potato",
  "🍢": "Oden",
  "🍣": "Sushi",
  "🍤": "Fried Shrimp",
  "🍥": "Fish Cake with Swirl",
  "🥮": "Moon Cake",
  "🍡": "Dango",
  "🥟": "Dumpling",
  "🥠": "Fortune Cookie",
  "🥡": "Takeout Box",
  "🦪": "Oyster",
  "🍦": "Soft Ice Cream",
  "🍧": "Shaved Ice",
  "🍨": "Ice Cream",
  "🍩": "Doughnut",
  "🍪": "Cookie",
  "🎂": "Birthday Cake",
  "🍰": "Shortcake",
  "🧁": "Cupcake",
  "🥧": "Pie",
  "🍫": "Chocolate Bar",
  "🍬": "Candy",
  "🍭": "Lollipop",
  "🍮": "Custard",
  "🍯": "Honey Pot",
  "🍼": "Baby Bottle",
  "🥛": "Glass of Milk",
  "☕": "Hot Beverage",
  "🫖": "Teapot",
  "🍵": "Teacup Without Handle",
  "🍶": "Sake",
  "🍾": "Bottle with Popping Cork",
  "🍷": "Wine Glass",
  "🍸": "Cocktail Glass",
  "🍹": "Tropical Drink",
  "🍺": "Beer Mug",
  "🍻": "Clinking Beer Mugs",
  "🥂": "Clinking Glasses",
  "🥃": "Tumbler Glass",
  "🥤": "Cup with Straw",
  "🧋": "Bubble Tea",
  "🧃": "Beverage Box",
  "🧉": "Mate",
  "🧊": "Ice",
  "🥢": "Chopsticks",
  "🍴": "Fork and Knife",
  "🥄": "Spoon",
  "🐗": "Animal and Nature: Boar",
  "🐽": "Animal and Nature: Pig Nose",
  "🐏": "Animal and Nature: Ram",
  "🐑": "Animal and Nature: Ewe",
  "🐐": "Animal and Nature: Goat",
  "🐪": "Animal and Nature: Camel",
  "🐫": "Animal and Nature: Two-Hump Camel",
  "🦙": "Animal and Nature: Llama",
  "🦒": "Animal and Nature: Giraffe",
  "🐘": "Animal and Nature: Elephant",
  "🦏": "Animal and Nature: Rhinoceros",
  "🦛": "Animal and Nature: Hippopotamus",
  "🐭": "Animal and Nature: Mouse Face",
  "🐁": "Animal and Nature: Mouse",
  "🐀": "Animal and Nature: Rat",
  "🐹": "Animal and Nature: Hamster",
  "🐰": "Animal and Nature: Rabbit Face",
  "🐇": "Animal and Nature: Rabbit",
  "🐿️": "Animal and Nature: Chipmunk",
  "🦔": "Animal and Nature: Hedgehog",
  "🦇": "Animal and Nature: Bat",
  "🐻": "Animal and Nature: Bear",
  "🐨": "Animal and Nature: Koala",
  "🐼": "Animal and Nature: Panda",
  "🦥": "Animal and Nature: Sloth",
  "🦦": "Animal and Nature: Otter",
  "🦨": "Animal and Nature: Skunk",
  "🦘": "Animal and Nature: Kangaroo",
  "🦡": "Animal and Nature: Badger",
  "🐾": "Animal and Nature: Paw Prints",
  "🦃": "Animal and Nature: Turkey",
  "🐔": "Animal and Nature: Chicken",
  "🐓": "Animal and Nature: Rooster",
  "🐣": "Animal and Nature: Hatching Chick",
  "🦠": "Animal and Nature: Microbe",
  "💐": "Animal and Nature: Bouquet",
  "🌸": "Animal and Nature: Cherry Blossom",
  "💮": "Animal and Nature: White Flower",
  "🏵️": "Animal and Nature: Rosette",
  "🌹": "Animal and Nature: Rose",
  "🥀": "Animal and Nature: Wilted Flower",
  "🌺": "Animal and Nature: Hibiscus",
  "🌻": "Animal and Nature: Sunflower",
  "🌼": "Animal and Nature: Blossom",
  "🌷": "Animal and Nature: Tulip",
  "🌱": "Animal and Nature: Seedling",
  "🌲": "Animal and Nature: Evergreen Tree",
  "🕴️": "Activity and Sports: Person in Suit Levitating",
  "🧗": "Activity and Sports: Person Climbing",
  "🧗‍♂️": "Activity and Sports: Man Climbing",
  "🧗‍♀️": "Activity and Sports: Woman Climbing",
  "🤺": "Activity and Sports: Person Fencing",
  "🏇": "Activity and Sports: Horse Racing",
  "⛷️": "Activity and Sports: Skier",
  "🏂": "Activity and Sports: Snowboarder",
  "🏌️": "Activity and Sports: Person Golfing",
  "🏌️‍♂️": "Activity and Sports: Man Golfing",
  "🏌️‍♀️": "Activity and Sports: Woman Golfing",
  "🏄": "Activity and Sports: Person Surfing",
  "🏄‍♂️": "Activity and Sports: Man Surfing",
  "🏄‍♀️": "Activity and Sports: Woman Surfing",
  "🚣": "Activity and Sports: Person Rowing Boat",
  "🚣‍♂️": "Activity and Sports: Man Rowing Boat",
  "🚣‍♀️": "Activity and Sports: Woman Rowing Boat",
  "🏊": "Activity and Sports: Person Swimming",
  "🏊‍♂️": "Activity and Sports: Man Swimming",
  "🏊‍♀️": "Activity and Sports: Woman Swimming",
  "⛹️": "Activity and Sports: Person Bouncing Ball",
  "⛹️‍♂️": "Activity and Sports: Man Bouncing Ball",
  "⛹️‍♀️": "Activity and Sports: Woman Bouncing Ball",
  "🏋️": "Activity and Sports: Person Lifting Weights",
  "🏋️‍♂️": "Activity and Sports: Man Lifting Weights",
  "🏋️‍♀️": "Activity and Sports: Woman Lifting Weights",
  "🚴": "Activity and Sports: Person Biking",
  "🚴‍♂️": "Activity and Sports: Man Biking",
  "🚴‍♀️": "Activity and Sports: Woman Biking",
  "🚵": "Activity and Sports: Person Mountain Biking",
  "🚵‍♂️": "Activity and Sports: Man Mountain Biking",
  "🚵‍♀️": "Activity and Sports: Woman Mountain Biking",
  "🤸": "Activity and Sports: Person Cartwheeling",
  "🤹‍♀️": "Activity and Sports: Woman Juggling",
  "🧘": "Activity and Sports: Person in Lotus Position",
  "🧘‍♂️": "Activity and Sports: Man in Lotus Position",
  "🧘‍♀️": "Activity and Sports: Woman in Lotus Position",
  "🎪": "Activity and Sports: Circus Tent",
  "🛹": "Activity and Sports: Skateboard",
  "🛶": "Activity and Sports: Canoe",
  "🎗️": "Activity and Sports: Reminder Ribbon",
  "🎟️": "Activity and Sports: Admission Tickets",
  "🎫": "Activity and Sports: Ticket",
  "🎖️": "Activity and Sports: Military Medal",
  "🏆": "Activity and Sports: Trophy",
  "🧩": "Activity and Sports: Puzzle Piece",
  "♟️": "Activity and Sports: Chess Pawn",
  "🎭": "Activity and Sports: Performing Arts",
  "🎨": "Activity and Sports: Artist Palette",
  "🗨️": "Symbols: Left Speech Bubble",
  "🗯️": "Symbols: Right Anger Bubble",
  "💭": "Symbols: Thought Balloon",
  "💤": "Symbols: Zzz",
  "♨️": "Symbols: Hot Springs",
  "💈": "Symbols: Barber Pole",
  "🛑": "Symbols: Stop Sign",
  "🕛": "Symbols: Twelve O’Clock",
  "🦁": "Animal and Nature: Lion",
  "🐯": "Animal and Nature: Tiger Face"
};
var inputText = "";
var emojisWeKnow = Object.keys(emojiDictionary);
export default function App() {
  const [meaning, setMeaning] = useState("");

  function emojiInputHandler(event) {
    console.log(event.target.value);
    var userInput = event.target.value;
    inputText = event.target.value;
    var meaning = emojiDictionary[userInput];
    if (meaning === undefined) {
      meaning = "We don't have this in our database";
    }
    // console.log(meaning);
    setMeaning(meaning);
  }
  function emojiClickHandler(emoji) {
    var meaning = emojiDictionary[emoji];
    setMeaning(meaning);
    // console.log(emoji);
  }
  return (
    <div className="App">
      <h1>Emoji Dictionary</h1>
      <input onChange={emojiInputHandler}></input>
      <h2>{meaning}</h2> <h3>Emojis we know</h3>
      <div className="contain">
        {emojisWeKnow.map(function (emoji) {
          return (
            <span
              className="emo"
              onClick={() => emojiClickHandler(emoji)}
              key={emoji}
            >
              {" "}
              {emoji}{" "}
            </span>
          );
        })}
      </div>
      <div className="foot">
        <span className="portf">
          <a href="https://ritik-omega.netlify.app/"> Portfolio </a>
        </span>
      </div>
    </div>
  );
}
